@SSCCProject_HostAddress = https://localhost:7158

GET {{SSCCProject_HostAddress}}/weatherforecast/
Accept: application/json
   

### Create new Logistic Unit
POST {{SSCCProject_HostAddress}}/api/LogisticUnit
Content-Type: application/json
Accept: application/json

{
  "name": "5 oil bottle Carton",
  "type": 1,
  "itemsCount": 5,
  "weightInKg": 10.5,
  "lengthInCm": 10,
  "widthInCm": 70,
  "heightInCm": 150,
  "sgtins": [
    "6225000055513000003",
    "6225000055520000004"
  ]
}
 
  
### Create SSCC for logistic unit
POST {{SSCCProject_HostAddress}}/api/SSCC/Create-sscc-for-logistic-unit
Content-Type: application/json
Accept: application/json

{
  "logisticUnitId": "c9bae2f5-5812-471b-f5e7-08de0995154f",
  "gs1CompanyPrefix": "622500005980",
  "extensionDigit": 0
}

### Create SSCC 
POST {{SSCCProject_HostAddress}}/api/SSCC/Create-sscc
Content-Type: application/json
Accept: application/json

{ 
  "gs1CompanyPrefix": "622500005980",
  "extensionDigit": 0
}
 

### Export SSCC Label as PNG Image 
POST {{SSCCProject_HostAddress}}/api/SSCC/export-label?ssccCode=062250000598093003
Accept: text/plain
 